LEAGUE_CONFIG = {
    'NFL': {
        'sport': 'football',
        'league': 'nfl',
        'duration_hours': 3.5,
        'team_based': True,
    },
    'NBA': {
        'sport': 'basketball',
        'league': 'nba',
        'duration_hours': 2.5,
        'team_based': True,
    },
    'MLB': {
        'sport': 'baseball',
        'league': 'mlb',
        'duration_hours': 3.0,
        'team_based': True,
    },
    'NHL': {
        'sport': 'hockey',
        'league': 'nhl',
        'duration_hours': 2.5,
        'team_based': True,
    },
    'MLS': {
        'sport': 'soccer',
        'league': 'usa.1',
        'duration_hours': 2.0,
        'team_based': True,
    },
    'WNBA': {
        'sport': 'basketball',
        'league': 'wnba',
        'duration_hours': 2.5,
        'team_based': True,
    },
    'SEC': {
        'sport': 'football',
        'league': 'college-football',
        'duration_hours': 3.5,
        'team_based': True,
        'teams': [
            {"id": "333",  "name": "Alabama Crimson Tide"},
            {"id": "8",    "name": "Arkansas Razorbacks"},
            {"id": "2",    "name": "Auburn Tigers"},
            {"id": "57",   "name": "Florida Gators"},
            {"id": "61",   "name": "Georgia Bulldogs"},
            {"id": "96",   "name": "Kentucky Wildcats"},
            {"id": "99",   "name": "LSU Tigers"},
            {"id": "344",  "name": "Mississippi State Bulldogs"},
            {"id": "142",  "name": "Missouri Tigers"},
            {"id": "201",  "name": "Oklahoma Sooners"},
            {"id": "145",  "name": "Ole Miss Rebels"},
            {"id": "2579", "name": "South Carolina Gamecocks"},
            {"id": "2633", "name": "Tennessee Volunteers"},
            {"id": "245",  "name": "Texas A&M Aggies"},
            {"id": "251",  "name": "Texas Longhorns"},
            {"id": "238",  "name": "Vanderbilt Commodores"},
        ],
    },
    'ACC': {
        'sport': 'football',
        'league': 'college-football',
        'duration_hours': 3.5,
        'team_based': True,
        'teams': [
            {"id": "103",  "name": "Boston College Eagles"},
            {"id": "25",   "name": "California Golden Bears"},
            {"id": "228",  "name": "Clemson Tigers"},
            {"id": "150",  "name": "Duke Blue Devils"},
            {"id": "52",   "name": "Florida State Seminoles"},
            {"id": "59",   "name": "Georgia Tech Yellow Jackets"},
            {"id": "97",   "name": "Louisville Cardinals"},
            {"id": "2390", "name": "Miami Hurricanes"},
            {"id": "152",  "name": "NC State Wolfpack"},
            {"id": "153",  "name": "North Carolina Tar Heels"},
            {"id": "221",  "name": "Pittsburgh Panthers"},
            {"id": "2567", "name": "SMU Mustangs"},
            {"id": "24",   "name": "Stanford Cardinal"},
            {"id": "183",  "name": "Syracuse Orange"},
            {"id": "258",  "name": "Virginia Cavaliers"},
            {"id": "259",  "name": "Virginia Tech Hokies"},
            {"id": "154",  "name": "Wake Forest Demon Deacons"},
        ],
    },
    'Big 12': {
        'sport': 'football',
        'league': 'college-football',
        'duration_hours': 3.5,
        'team_based': True,
        'teams': [
            {"id": "12",   "name": "Arizona Wildcats"},
            {"id": "9",    "name": "Arizona State Sun Devils"},
            {"id": "239",  "name": "Baylor Bears"},
            {"id": "252",  "name": "BYU Cougars"},
            {"id": "2132", "name": "Cincinnati Bearcats"},
            {"id": "38",   "name": "Colorado Buffaloes"},
            {"id": "248",  "name": "Houston Cougars"},
            {"id": "66",   "name": "Iowa State Cyclones"},
            {"id": "2305", "name": "Kansas Jayhawks"},
            {"id": "2306", "name": "Kansas State Wildcats"},
            {"id": "197",  "name": "Oklahoma State Cowboys"},
            {"id": "2628", "name": "TCU Horned Frogs"},
            {"id": "2641", "name": "Texas Tech Red Raiders"},
            {"id": "2116", "name": "UCF Knights"},
            {"id": "254",  "name": "Utah Utes"},
            {"id": "277",  "name": "West Virginia Mountaineers"},
        ],
    },
    'Big Ten': {
        'sport': 'football',
        'league': 'college-football',
        'duration_hours': 3.5,
        'team_based': True,
        'teams': [
            {"id": "356",  "name": "Illinois Fighting Illini"},
            {"id": "84",   "name": "Indiana Hoosiers"},
            {"id": "2294", "name": "Iowa Hawkeyes"},
            {"id": "127",  "name": "Michigan State Spartans"},
            {"id": "130",  "name": "Michigan Wolverines"},
            {"id": "135",  "name": "Minnesota Golden Gophers"},
            {"id": "158",  "name": "Nebraska Cornhuskers"},
            {"id": "77",   "name": "Northwestern Wildcats"},
            {"id": "194",  "name": "Ohio State Buckeyes"},
            {"id": "2483", "name": "Oregon Ducks"},
            {"id": "213",  "name": "Penn State Nittany Lions"},
            {"id": "2509", "name": "Purdue Boilermakers"},
            {"id": "164",  "name": "Rutgers Scarlet Knights"},
            {"id": "26",   "name": "UCLA Bruins"},
            {"id": "30",   "name": "USC Trojans"},
            {"id": "264",  "name": "Washington Huskies"},
            {"id": "275",  "name": "Wisconsin Badgers"},
        ],
    },
    'PGA': {
        'sport': 'golf',
        'league': 'pga',
        'duration_hours': 8.0,
        'team_based': False,
        # PGA events are multi-day tournaments; each round is 1 all-day block
    },
    'NASCAR': {
        'sport': 'racing',
        'league': 'nascar-premier',
        'duration_hours': 4.0,
        'team_based': False,
    },
    'UFC': {
        'sport': 'mma',
        'league': 'ufc',
        'duration_hours': 5.0,
        'team_based': False,
    },
}

LEAGUE_ALIASES = {
    'FOOTBALL': 'NFL',
    'BASKETBALL': 'NBA',
    'HOCKEY': 'NHL',
    'BASEBALL': 'MLB',
    'SOCCER': 'MLS',
    'GOLF': 'PGA',
    'PGA TOUR': 'PGA',
    'RACING': 'NASCAR',
    'CUP SERIES': 'NASCAR',
    'MMA': 'UFC',
    'MIXED MARTIAL ARTS': 'UFC',
    "WOMEN'S BASKETBALL": 'WNBA',
    'WOMENS BASKETBALL': 'WNBA',
    'BIG12': 'Big 12',
    'BIGTEN': 'Big Ten',
    'BIG TEN': 'Big Ten',
    'BIG 12': 'Big 12',
}

# Groups leagues by category for the UI dropdown
LEAGUE_GROUPS = {
    'Professional Leagues': ['NFL', 'NBA', 'MLB', 'NHL', 'MLS', 'WNBA'],
    'College Football': ['SEC', 'ACC', 'Big 12', 'Big Ten'],
    'Other': ['PGA', 'NASCAR', 'UFC'],
}
